"""
Заполнение Word-шаблонов из словаря данных.
"""

import copy
import io
import re
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

from docx import Document
from docxtpl import DocxTemplate
from jinja2 import Environment
from lxml import etree

from . import filters
from .config import load_settings


# Переменные, которые программа подставляет автоматически и которые
# не нужно показывать пользователю в форме (это «системные» имена).
SYSTEM_VARIABLES = {'настройки'}

_W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
_MAX_FIELD_LEN = 2000


def _declensions_from_settings(settings):
    """Извлечь словарь склонений из объекта настроек."""
    try:
        raw = settings['склонения']
    except (KeyError, TypeError):
        return {}
    if not raw:
        return {}
    result = {}
    for phrase, forms in raw.items():
        if isinstance(forms, dict):
            result[str(phrase)] = {k: str(v) for k, v in forms.items() if v}
    return result


def list_template_variables(template_path, settings=None):
    """Вернуть отсортированный список переменных, найденных в шаблоне."""
    env = Environment()
    if settings is None:
        settings = load_settings()
    filters.install(env, declensions=_declensions_from_settings(settings))
    doc = DocxTemplate(str(template_path))
    variables = doc.get_undeclared_template_variables(env)
    return sorted(v for v in variables if v not in SYSTEM_VARIABLES)


DESCRIPTION_STOP_STRINGS = (
    'generated by python-docx',
    'created with python-docx',
    'python-docx',
)


def describe_template(template_path):
    """Вернуть краткое описание шаблона из свойств файла."""
    try:
        doc = Document(str(template_path))
        props = doc.core_properties
        for attr in ('comments', 'subject', 'title'):
            value = getattr(props, attr, None)
            if not value:
                continue
            text = str(value).strip()
            if not text:
                continue
            low = text.lower()
            if any(stop in low for stop in DESCRIPTION_STOP_STRINGS):
                continue
            return text
    except Exception:
        pass
    return ''


def _direct_children(parent, tag):
    """Прямые дочерние элементы с данным тегом (без вложенных таблиц)."""
    return [child for child in parent if child.tag == tag]


def _cell_grid_span(tc):
    tc_pr = tc.find(f'{_W}tcPr')
    if tc_pr is None:
        return 1
    grid_span = tc_pr.find(f'{_W}gridSpan')
    if grid_span is None:
        return 1
    try:
        return max(1, int(grid_span.get(f'{_W}val') or 1))
    except ValueError:
        return 1


def _cell_width(tc):
    tc_pr = tc.find(f'{_W}tcPr')
    if tc_pr is None:
        return None
    tc_w = tc_pr.find(f'{_W}tcW')
    if tc_w is None:
        return None
    raw = tc_w.get(f'{_W}w')
    if raw and str(raw).isdigit():
        return int(raw)
    return None


def _row_span_total(tr):
    return sum(_cell_grid_span(tc) for tc in _direct_children(tr, f'{_W}tc'))


def _table_width(tbl, grid_widths):
    tbl_pr = tbl.find(f'{_W}tblPr')
    if tbl_pr is not None:
        tbl_w = tbl_pr.find(f'{_W}tblW')
        if tbl_w is not None:
            raw = tbl_w.get(f'{_W}w')
            if raw and str(raw).isdigit() and int(raw) > 0:
                return int(raw)
    if grid_widths and sum(grid_widths) > 0:
        return sum(grid_widths)
    return 8000


def _preferred_grid_widths(tbl, target_cols, grid_widths):
    """Ширины колонок: из строки без merge, иначе пропорционально старой сетке."""
    for tr in _direct_children(tbl, f'{_W}tr'):
        cells = _direct_children(tr, f'{_W}tc')
        if len(cells) != target_cols:
            continue
        if any(_cell_grid_span(tc) != 1 for tc in cells):
            continue
        widths = [_cell_width(tc) for tc in cells]
        if all(w and w > 0 for w in widths):
            return widths

    total = _table_width(tbl, grid_widths)
    if grid_widths and len(grid_widths) == target_cols and sum(grid_widths) > 0:
        return grid_widths
    base = total // target_cols
    rem = total - base * target_cols
    return [base + (1 if i < rem else 0) for i in range(target_cols)]


def _fix_table_grid(tbl):
    """Выровнять w:tblGrid по сумме gridSpan прямых ячеек. Вернуть True, если меняли."""
    rows = _direct_children(tbl, f'{_W}tr')
    if not rows:
        return False

    target_cols = max(_row_span_total(tr) for tr in rows)
    if target_cols <= 0:
        return False

    tbl_grid = tbl.find(f'{_W}tblGrid')
    if tbl_grid is None:
        tbl_grid = etree.Element(f'{_W}tblGrid')
        tbl_pr = tbl.find(f'{_W}tblPr')
        if tbl_pr is not None:
            tbl_pr.addnext(tbl_grid)
        else:
            tbl.insert(0, tbl_grid)

    grid_cols = _direct_children(tbl_grid, f'{_W}gridCol')
    grid_widths = []
    for gc in grid_cols:
        raw = gc.get(f'{_W}w')
        grid_widths.append(int(raw) if raw and str(raw).isdigit() else 0)

    if len(grid_cols) == target_cols:
        return False

    new_widths = _preferred_grid_widths(tbl, target_cols, grid_widths)
    for gc in list(tbl_grid):
        tbl_grid.remove(gc)
    for width in new_widths:
        gc = etree.SubElement(tbl_grid, f'{_W}gridCol')
        gc.set(f'{_W}w', str(max(1, int(width))))
    return True


def _restore_grids_from_template(out_root, template_path):
    """Скопировать w:tblGrid из исходного шаблона (docxtpl их портит)."""
    try:
        tpl_xml = zipfile.ZipFile(template_path).read('word/document.xml')
    except (OSError, KeyError, zipfile.BadZipFile):
        return False
    tpl_root = etree.fromstring(tpl_xml)
    tpl_tables = list(tpl_root.iter(f'{_W}tbl'))
    out_tables = list(out_root.iter(f'{_W}tbl'))
    if len(tpl_tables) != len(out_tables):
        return False

    changed = False
    for tpl_tbl, out_tbl in zip(tpl_tables, out_tables):
        tpl_grid = tpl_tbl.find(f'{_W}tblGrid')
        out_grid = out_tbl.find(f'{_W}tblGrid')
        if tpl_grid is None:
            continue
        tpl_cols = _direct_children(tpl_grid, f'{_W}gridCol')
        out_cols = _direct_children(out_grid, f'{_W}gridCol') if out_grid is not None else []
        if out_grid is not None and len(tpl_cols) == len(out_cols):
            same = all(
                (a.get(f'{_W}w') or '') == (b.get(f'{_W}w') or '')
                for a, b in zip(tpl_cols, out_cols)
            )
            if same:
                continue
        new_grid = copy.deepcopy(tpl_grid)
        if out_grid is not None:
            out_tbl.replace(out_grid, new_grid)
        else:
            tbl_pr = out_tbl.find(f'{_W}tblPr')
            if tbl_pr is not None:
                tbl_pr.addnext(new_grid)
            else:
                out_tbl.insert(0, new_grid)
        changed = True
    return changed


def repair_document_tables(docx_path, template_path=None):
    """Починить сетку таблиц после docxtpl (критично для формы ПКО КО-1).

    docxtpl иногда добавляет лишние w:gridCol во внешних таблицах с вложенными
    таблицами — Word отказывается открывать файл. Надёжный путь: вернуть
    tblGrid из исходного шаблона; запасной — пересчитать по прямым ячейкам.
    """
    path = Path(docx_path)
    with zipfile.ZipFile(path, 'r') as zin:
        try:
            xml_bytes = zin.read('word/document.xml')
        except KeyError:
            return
        other = [(info.filename, zin.read(info.filename)) for info in zin.infolist()
                 if info.filename != 'word/document.xml']

    root = etree.fromstring(xml_bytes)
    changed = False
    if template_path is not None:
        changed = _restore_grids_from_template(root, template_path) or changed
    for tbl in root.iter(f'{_W}tbl'):
        if _fix_table_grid(tbl):
            changed = True
    if not changed:
        return

    new_xml = etree.tostring(
        root, xml_declaration=True, encoding='UTF-8', standalone=True,
    )
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zout:
        zout.writestr('word/document.xml', new_xml)
        for name, data in other:
            zout.writestr(name, data)
    path.write_bytes(buf.getvalue())


def _sanitize_docx_value(value):
    """Подготовить значение к вставке в OOXML (без поломки XML).

    Jinja в DocxTemplate без autoescape: символы <>& и переносы из
    буфера/счётчика могут разрушить document.xml — Word не откроет файл.
    """
    if value is None:
        return ''
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value
    if isinstance(value, dict):
        return {str(k): _sanitize_docx_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_sanitize_docx_value(v) for v in value]
    text = str(value).replace('\r\n', '\n').replace('\r', '\n')
    text = re.sub(r'[\n\t]+', ' ', text)
    text = ''.join(ch for ch in text if ord(ch) >= 32)
    text = re.sub(r' {2,}', ' ', text).strip()
    if len(text) > _MAX_FIELD_LEN:
        text = text[:_MAX_FIELD_LEN].rstrip()
    return xml_escape(text)


def fill_template(template_path, output_path, context, settings=None):
    """
    Заполнить шаблон данными и сохранить результат.

    template_path — путь к .docx-шаблону с метками {{ переменная }}.
    output_path   — куда сохранить готовый документ.
    context       — словарь {имя_переменной: значение}.
    settings      — словарь/объект настроек организации (веб); иначе load_settings().
    """
    env = Environment()
    if settings is None:
        settings = load_settings()
    elif isinstance(settings, dict):
        from .config import settings_from_dict

        settings = settings_from_dict(settings)
    filters.install(env, declensions=_declensions_from_settings(settings))

    doc = DocxTemplate(str(template_path))

    # Подставить пустую строку для всех переменных, которых нет в данных,
    full_context = {var: '' for var in doc.get_undeclared_template_variables(env)}

    full_context['настройки'] = _sanitize_docx_value(settings)

    # Пользовательские поля перекрывают всё — на случай, если в реестре
    # вдруг окажется столбец с именем «настройки» или что-то системное.
    safe_context = {
        k: ('' if v is None else _sanitize_docx_value(v))
        for k, v in context.items()
    }
    full_context.update(safe_context)

    doc.render(full_context, jinja_env=env)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))
    repair_document_tables(output_path, template_path=template_path)
    return str(output_path)
